Traceback (most recent call last):
  File "/home/codespace/.python/current/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/__main__.py", line 48, in main
    args.func(args)
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 52, in command
    return func(*args, **kwargs)
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/utils/cli.py", line 112, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/cli/commands/webserver_command.py", line 494, in webserver
    monitor_gunicorn(gunicorn_master_proc.pid)
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/cli/commands/webserver_command.py", line 459, in monitor_gunicorn
    ).start()
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/cli/commands/webserver_command.py", line 218, in start
    self._check_workers()
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/cli/commands/webserver_command.py", line 263, in _check_workers
    sleep(10)
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/cli/commands/webserver_command.py", line 433, in kill_proc
    gunicorn_master_proc.terminate()
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/psutil/__init__.py", line 277, in wrapper
    raise NoSuchProcess(self.pid, self._name, msg=msg)
psutil.NoSuchProcess: process no longer exists (pid=2983)
